/* Generated by tools/png2lvgl.py. Do not edit. */
#pragma once
#include "lvgl/lvgl.h"

extern const lv_image_dsc_t icon_battery_charging;
extern const lv_image_dsc_t icon_battery_full;
extern const lv_image_dsc_t icon_battery_low;
extern const lv_image_dsc_t icon_battery_medium;
extern const lv_image_dsc_t icon_battery;
extern const lv_image_dsc_t icon_blinds;
extern const lv_image_dsc_t icon_cast;
extern const lv_image_dsc_t icon_chevron_left;
extern const lv_image_dsc_t icon_chevron_right;
extern const lv_image_dsc_t icon_film;
extern const lv_image_dsc_t icon_house;
extern const lv_image_dsc_t icon_lightbulb;
extern const lv_image_dsc_t icon_lock;
extern const lv_image_dsc_t icon_monitor;
extern const lv_image_dsc_t icon_moon;
extern const lv_image_dsc_t icon_pause;
extern const lv_image_dsc_t icon_play;
extern const lv_image_dsc_t icon_power;
extern const lv_image_dsc_t icon_settings;
extern const lv_image_dsc_t icon_skip_back;
extern const lv_image_dsc_t icon_skip_forward;
extern const lv_image_dsc_t icon_sofa_lg;
extern const lv_image_dsc_t icon_speaker;
extern const lv_image_dsc_t icon_square;
extern const lv_image_dsc_t icon_sun;
extern const lv_image_dsc_t icon_thermometer;
extern const lv_image_dsc_t icon_tv;
extern const lv_image_dsc_t icon_volume_2;
extern const lv_image_dsc_t icon_volume_x;
extern const lv_image_dsc_t icon_wifi;
