//! Bakes the built web UI into the binary.
//!
//! Embedded rather than shipped as files under `/opt/couch/www-config/`,
//! because a deploy of this thing is `scp` of one file. The config UI and the
//! API that serves it are versioned together - the frontend calls endpoints
//! this binary defines - and two artefacts that must match is two chances for
//! them not to. It also sidesteps the trap the setup portal already hit once:
//! anything that has to exist on disk at a fixed path is something a partial
//! copy can leave half-present, and a half-present web root serves a blank page
//! with no error anywhere.
//!
//! Hand-rolled rather than `rust-embed`, which would be a proc-macro, a
//! directory walker and a hashing crate to produce the same `include_bytes!`
//! table this writes in sixty lines.
//!
//! The dist directory not existing is not an error. It is the normal state of
//! a fresh clone, and failing the build there would mean nobody can compile the
//! API without first installing trunk. The daemon serves a page saying what to
//! run instead.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let dist = env::var("COUCH_WEB_DIST")
        .map(PathBuf::from)
        .unwrap_or_else(|_| {
            Path::new(env!("CARGO_MANIFEST_DIR")).join("../../web/couch-web/dist")
        });

    println!("cargo:rerun-if-env-changed=COUCH_WEB_DIST");
    println!("cargo:rerun-if-changed={}", dist.display());

    let mut files = Vec::new();
    collect(&dist, &dist, &mut files);
    files.sort();

    let mut out = String::from(
        "// Generated by build.rs. The web UI's dist directory, as a table.\n\
         pub static ASSETS: &[(&str, &[u8])] = &[\n",
    );
    for (route, path) in &files {
        println!("cargo:rerun-if-changed={}", path.display());
        out.push_str(&format!(
            "    ({:?}, include_bytes!({:?})),\n",
            route,
            path.display().to_string()
        ));
    }
    out.push_str("];\n");

    let dest = PathBuf::from(env::var("OUT_DIR").unwrap()).join("assets.rs");
    fs::write(&dest, out).expect("write generated asset table");

    if files.is_empty() {
        println!(
            "cargo:warning=no web assets at {} - run tools/build-webui.sh, or \
             couch-confd will serve a placeholder page",
            dist.display()
        );
    }
}

fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, out);
        } else if let Ok(rel) = path.strip_prefix(root) {
            // Routes are always slash-separated; this build may not be.
            let route = rel
                .components()
                .map(|c| c.as_os_str().to_string_lossy().into_owned())
                .collect::<Vec<_>>()
                .join("/");
            out.push((route, path));
        }
    }
}
