#!/usr/bin/env python3
"""Regenerate the model catalog and 24px alpha atlas from vendored Lucide SVGs.
Requires rsvg-convert and Pillow. No downloads are performed during builds.
"""
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from io import BytesIO
import subprocess
from PIL import Image

root = Path(__file__).resolve().parent.parent
source = root / 'assets/lucide'
files = sorted(source.glob('*.svg'), key=lambda p: p.stem)
assert files and len(files) < 65536
names = [p.stem for p in files]
legacy = ['Sofa', 'Bed', 'CookingPot', 'BookOpen', 'DoorOpen', 'Car', 'Trees',
          'Lamp', 'Tv', 'House', 'Lightbulb', 'Blinds', 'Thermometer', 'Speaker', 'Monitor']
legacy_names = ['sofa', 'bed', 'cooking-pot', 'book-open', 'door-open', 'car', 'trees',
                'lamp', 'tv', 'house', 'lightbulb', 'blinds', 'thermometer', 'speaker', 'monitor']
text = '// Generated by tools/build-icon-catalog.py; do not edit.\n'
text += 'pub const ICON_NAMES: &[&str] = &[\n' + ''.join(f'    "{name}",\n' for name in names) + '];\n'
text += 'pub const ALL_ICONS: &[Icon] = &[\n' + ''.join(f'    Icon({i}),\n' for i in range(len(names))) + '];\n'
text += '#[allow(non_upper_case_globals)]\nimpl Icon {\n'
text += ''.join(f'    pub const {variant}: Self = Self({names.index(name)});\n' for variant, name in zip(legacy, legacy_names))
text += '}\n'
(root / 'model/couch-model/src/icon_catalog.rs').write_text(text)
def raster(path):
    svg = path.read_text().replace('currentColor', '#ffffff').replace('stroke-width="2"', 'stroke-width="2.2"')
    png = subprocess.check_output(['rsvg-convert', '-w', '24', '-h', '24'], input=svg.encode())
    return Image.open(BytesIO(png)).convert('RGBA').getchannel('A').tobytes()
with ThreadPoolExecutor(max_workers=8) as workers:
    alpha = b''.join(workers.map(raster, files))
(root / 'ui/couch-gui/assets/lucide.alpha').write_bytes(alpha)
print(f'{len(names)} icons, {len(alpha)} bytes of alpha masks')
