#!/usr/bin/env python3
"""Turn the splash icon into a C header fbcon can draw.

fbcon runs from the initramfs long before LVGL exists, so it cannot use the
LVGL asset in gui/icons.c. Same artwork, different consumer: an 8-bit alpha
bitmap it composites over the background itself.
"""
import sys
from PIL import Image

src = sys.argv[1] if len(sys.argv) > 1 else "gui/icons/png/sofa_lg.png"
out = sys.argv[2] if len(sys.argv) > 2 else "src/logo.h"

im = Image.open(src).convert("RGBA")
w, h = im.size
alpha = im.getchannel("A").tobytes()

with open(out, "w") as f:
    f.write("/* Generated by tools/mklogo.py from %s - do not edit. */\n" % src)
    f.write("#pragma once\n\n")
    f.write("#define LOGO_W %d\n#define LOGO_H %d\n\n" % (w, h))
    f.write("static const unsigned char logo_a8[LOGO_W * LOGO_H] = {\n")
    for i in range(0, len(alpha), 16):
        f.write("    " + ",".join("%3d" % b for b in alpha[i:i+16]) + ",\n")
    f.write("};\n")
print("%s: %dx%d alpha, %d bytes" % (out, w, h, len(alpha)))
