#!/usr/bin/env python3
"""Turn the boot wordmark into a C header fbcon can draw.

fbcon runs from the initramfs before the GUI. The canonical boot wordmark
is converted to an 8-bit coverage bitmap for its framebuffer renderer.
"""
import sys
from PIL import Image

src = sys.argv[1] if len(sys.argv) > 1 else "assets/boot/couch.png"
out = sys.argv[2] if len(sys.argv) > 2 else "src/logo.h"

im = Image.open(src).convert("RGBA")
w, h = im.size
# The canonical boot wordmark is white on opaque black. Its luminance is
# the coverage mask; alpha alone would render an opaque rectangle.
mask = im.convert("L") if src.endswith("assets/boot/couch.png") else im.getchannel("A")
bounds = mask.getbbox()
if bounds:
    mask = mask.crop(bounds)
w, h = mask.size
alpha = mask.tobytes()

with open(out, "w") as f:
    f.write("/* Generated by tools/mklogo.py from %s - do not edit. */\n" % src)
    f.write("#pragma once\n\n")
    f.write("#define LOGO_W %d\n#define LOGO_H %d\n\n" % (w, h))
    f.write("static const unsigned char logo_a8[LOGO_W * LOGO_H] = {\n")
    for i in range(0, len(alpha), 16):
        f.write("    " + ",".join("%3d" % b for b in alpha[i:i+16]) + ",\n")
    f.write("};\n")
print("%s: %dx%d alpha, %d bytes" % (out, w, h, len(alpha)))
