#!/usr/bin/env python3
"""Convert PNGs to LVGL A8 image descriptors, emitted as one C file.

A8 keeps only the alpha channel, so an icon is one byte per pixel and LVGL
recolours it at draw time - the equivalent of Lucide's currentColor, and a
quarter the size of ARGB8888.

LVGL ships scripts/LVGLImage.py for this but it needs pypng; Pillow is already
available here, and doing it directly avoids adding a dependency.
"""
import sys, os, re
from PIL import Image

def cname(path):
    return "icon_" + re.sub(r"[^a-z0-9]+", "_", os.path.splitext(os.path.basename(path))[0].lower())

def main(out_c, out_h, files):
    decls, blobs = [], []
    for f in sorted(files):
        img = Image.open(f).convert("RGBA")
        w, h = img.size
        alpha = img.getchannel("A").tobytes()
        assert len(alpha) == w * h
        n = cname(f)
        rows = []
        for y in range(h):
            row = alpha[y * w:(y + 1) * w]
            rows.append("    " + ",".join(f"0x{b:02x}" for b in row) + ",")
        blobs.append(
            f"static const uint8_t {n}_map[] = {{\n" + "\n".join(rows) + "\n};\n\n"
            f"const lv_image_dsc_t {n} = {{\n"
            f"    .header.magic  = LV_IMAGE_HEADER_MAGIC,\n"
            f"    .header.cf     = LV_COLOR_FORMAT_A8,\n"
            f"    .header.w      = {w},\n"
            f"    .header.h      = {h},\n"
            f"    .header.stride = {w},\n"
            f"    .data_size     = sizeof({n}_map),\n"
            f"    .data          = {n}_map,\n"
            f"}};\n")
        decls.append(f"extern const lv_image_dsc_t {n};")
        print(f"  {n}: {w}x{h}, {w*h} bytes")

    with open(out_c, "w") as c:
        c.write("/* Generated by tools/png2lvgl.py from Lucide icons (ISC). Do not edit. */\n")
        c.write('#include "lvgl/lvgl.h"\n\n')
        c.write("\n".join(blobs))
    with open(out_h, "w") as hdr:
        hdr.write("/* Generated by tools/png2lvgl.py. Do not edit. */\n#pragma once\n")
        hdr.write('#include "lvgl/lvgl.h"\n\n')
        hdr.write("\n".join(decls) + "\n")
    print(f"wrote {out_c} ({os.path.getsize(out_c)} bytes) and {out_h}")

if __name__ == "__main__":
    if len(sys.argv) < 4:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2], sys.argv[3:])
